project_id = "mwcejojlbqpolplshjgj"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.public-stats]
    verify_jwt = false
  [functions.sandbox-demo]
