import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ROBOTO_REGULAR, ROBOTO_BOLD } from "./robotoFontData";

function registerCyrillicFont(doc: jsPDF) {
  doc.addFileToVFS("Roboto-Regular.ttf", ROBOTO_REGULAR);
  doc.addFont("Roboto-Regular.ttf", "Roboto", "normal");
  doc.addFileToVFS("Roboto-Bold.ttf", ROBOTO_BOLD);
  doc.addFont("Roboto-Bold.ttf", "Roboto", "bold");
  doc.setFont("Roboto", "normal");
}

interface RadarReportData {
  brandName: string;
  domain: string;
  date: string;
  lang: string;
  overallVisibility: number;
  somData: { label: string; value: number; status: string }[];
  radarChartData: { axis: string; value: number }[];
  sentimentDonut: { name: string; pct: number }[];
  sovDonut: { name: string; pct: number }[];
  competitorLeaderboard: { name: string; visibility: number; sentiment: string; isBrand: boolean }[];
  keywordSummary: { keyword: string; mainStatus: string; models: { model: string; status: string }[] }[];
}

interface SourcesReportData {
  sources: { domain: string; type: string; typeLabel: string; occurrenceCount: number }[];
  pieData: { name: string; value: number }[];
  totalSources: number;
  totalOccurrences: number;
}

const BRAND_COLOR: [number, number, number] = [124, 58, 237];
const DARK_BG: [number, number, number] = [15, 15, 20];
const CARD_BG: [number, number, number] = [25, 25, 35];
const TEXT_WHITE: [number, number, number] = [240, 240, 245];
const TEXT_MUTED: [number, number, number] = [150, 150, 165];
const GREEN: [number, number, number] = [34, 197, 94];
const YELLOW: [number, number, number] = [234, 179, 8];
const RED: [number, number, number] = [239, 68, 68];

function getTrafficLightColor(value: number): [number, number, number] {
  if (value >= 70) return GREEN;
  if (value >= 30) return YELLOW;
  return RED;
}

function t(ru: string, en: string, lang: string): string {
  return lang === "ru" ? ru : en;
}

function getStatusLabel(status: string, lang: string): string {
  const map: Record<string, [string, string]> = {
    captured: ["Захвачен", "Captured"],
    displaced: ["Вытеснен", "Displaced"],
    opportunity: ["Возможность", "Opportunity"],
    full_capture: ["Полный захват", "Full Capture"],
  };
  const pair = map[status];
  return pair ? t(pair[0], pair[1], lang) : status;
}

function getSentimentLabel(sentiment: string, lang: string): string {
  const map: Record<string, [string, string]> = {
    positive: ["Позитивный", "Positive"],
    neutral: ["Нейтральный", "Neutral"],
    negative: ["Негативный", "Negative"],
  };
  const pair = map[sentiment];
  return pair ? t(pair[0], pair[1], lang) : sentiment;
}

function addHeader(doc: jsPDF, brandName: string, domain: string, date: string, lang: string) {
  doc.setFillColor(...DARK_BG);
  doc.rect(0, 0, 210, 40, "F");
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 40, 210, 1.5, "F");

  doc.setTextColor(...TEXT_WHITE);
  doc.setFontSize(18);
  doc.text(t("GEO Радар — Отчёт", "GEO Radar Report", lang), 15, 18);

  doc.setFontSize(10);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(`${brandName} — ${domain}`, 15, 27);
  doc.text(date, 15, 34);

  doc.setTextColor(...TEXT_WHITE);
  doc.setFontSize(9);
  doc.text("seo-modul.pro", 195, 18, { align: "right" });
}

function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(15, y, 3, 8, "F");
  doc.setTextColor(...TEXT_WHITE);
  doc.setFontSize(13);
  doc.text(title, 22, y + 6);
  return y + 14;
}

function addKpiRow(doc: jsPDF, items: { label: string; value: string; color?: [number, number, number] }[], y: number): number {
  const boxW = (180 - (items.length - 1) * 4) / items.length;
  items.forEach((item, i) => {
    const x = 15 + i * (boxW + 4);
    doc.setFillColor(...CARD_BG);
    doc.roundedRect(x, y, boxW, 22, 2, 2, "F");
    doc.setTextColor(...TEXT_MUTED);
    doc.setFontSize(8);
    doc.text(item.label, x + boxW / 2, y + 8, { align: "center" });
    doc.setTextColor(...(item.color || TEXT_WHITE));
    doc.setFontSize(14);
    doc.text(item.value, x + boxW / 2, y + 18, { align: "center" });
  });
  return y + 28;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 280) {
    doc.addPage();
    doc.setFillColor(...DARK_BG);
    doc.rect(0, 0, 210, 297, "F");
    return 15;
  }
  return y;
}

function addFooters(doc: jsPDF, lang: string) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFillColor(...CARD_BG);
    doc.rect(0, 287, 210, 10, "F");
    doc.setTextColor(...TEXT_MUTED);
    doc.setFontSize(7);
    doc.text(
      t(`Стр. ${i} из ${pageCount}`, `Page ${i} of ${pageCount}`, lang),
      105, 293, { align: "center" }
    );
    doc.text(
      t("Сгенерировано СЕО-Модуль — seo-modul.pro", "Generated by SEO-Module — seo-modul.pro", lang),
      15, 293
    );
  }
}

export function generateRadarPdf(data: RadarReportData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  registerCyrillicFont(doc);
  const lang = data.lang || "ru";

  doc.setFillColor(...DARK_BG);
  doc.rect(0, 0, 210, 297, "F");

  addHeader(doc, data.brandName, data.domain, data.date, lang);

  let y = 50;

  // ── KPI Overview ──
  y = addSectionTitle(doc, t("Обзор видимости", "Visibility Overview", lang), y);
  const visColor = getTrafficLightColor(data.overallVisibility);
  y = addKpiRow(doc, [
    { label: t("Общая видимость", "Overall Visibility", lang), value: `${data.overallVisibility}%`, color: visColor },
    { label: t("Моделей", "Models Tracked", lang), value: String(data.somData.length) },
    { label: t("Ключевых слов", "Keywords", lang), value: String(data.keywordSummary.length) },
    { label: t("Конкурентов", "Competitors", lang), value: String(data.competitorLeaderboard.filter(c => !c.isBrand).length) },
  ], y);

  // ── SOM table ──
  y = checkPageBreak(doc, y, 50);
  y = addSectionTitle(doc, t("Доля в моделях (SoM)", "Share of Model (SoM)", lang), y);
  autoTable(doc, {
    startY: y,
    head: [[t("Модель", "Model", lang), t("Видимость %", "Visibility %", lang), t("Статус", "Status", lang)]],
    body: data.somData.map(d => [d.label, `${d.value}%`, getStatusLabel(d.status, lang)]),
    theme: "plain",
    styles: { textColor: TEXT_WHITE, fillColor: DARK_BG, fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: CARD_BG, textColor: BRAND_COLOR, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [20, 20, 28] },
    margin: { left: 15, right: 15 },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // ── Radar axes ──
  if (data.radarChartData.length > 0) {
    y = checkPageBreak(doc, y, 45);
    y = addSectionTitle(doc, t("Оси видимости", "Visibility Dimensions", lang), y);
    autoTable(doc, {
      startY: y,
      head: [[t("Ось", "Dimension", lang), t("Балл", "Score", lang)]],
      body: data.radarChartData.map(d => [d.axis, `${d.value}%`]),
      theme: "plain",
      styles: { textColor: TEXT_WHITE, fillColor: DARK_BG, fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: CARD_BG, textColor: BRAND_COLOR, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [20, 20, 28] },
      margin: { left: 15, right: 15 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ── Sentiment ──
  if (data.sentimentDonut.length > 0) {
    y = checkPageBreak(doc, y, 30);
    y = addSectionTitle(doc, t("Анализ тональности", "Sentiment Analysis", lang), y);
    const sentItems = data.sentimentDonut.map(s => ({
      label: s.name,
      value: `${s.pct}%`,
      color: s.name.includes("Позитив") || s.name.includes("Positive") ? GREEN : s.name.includes("Негатив") || s.name.includes("Negative") ? RED : TEXT_MUTED,
    }));
    y = addKpiRow(doc, sentItems as any, y);
  }

  // ── Share of Voice ──
  if (data.sovDonut.length > 0) {
    y = checkPageBreak(doc, y, 30);
    y = addSectionTitle(doc, t("Доля голоса (SoV)", "Share of Voice", lang), y);
    const sovItems = data.sovDonut.map(s => ({
      label: s.name,
      value: `${s.pct}%`,
      color: TEXT_WHITE as [number, number, number],
    }));
    y = addKpiRow(doc, sovItems as any, y);
  }

  // ── Competitor leaderboard ──
  if (data.competitorLeaderboard.length > 0) {
    y = checkPageBreak(doc, y, 50);
    y = addSectionTitle(doc, t("Рейтинг конкурентов", "Competitor Leaderboard", lang), y);
    autoTable(doc, {
      startY: y,
      head: [["#", t("Бренд / Домен", "Brand / Domain", lang), t("Видимость %", "Visibility %", lang), t("Тональность", "Sentiment", lang)]],
      body: data.competitorLeaderboard.map((c, i) => [
        String(i + 1),
        c.isBrand ? `* ${c.name}` : c.name,
        `${c.visibility}%`,
        getSentimentLabel(c.sentiment, lang),
      ]),
      theme: "plain",
      styles: { textColor: TEXT_WHITE, fillColor: DARK_BG, fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: CARD_BG, textColor: BRAND_COLOR, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [20, 20, 28] },
      margin: { left: 15, right: 15 },
      didParseCell: (hookData: any) => {
        if (hookData.section === "body" && hookData.column.index === 1) {
          const text = hookData.cell.raw as string;
          if (text.startsWith("*")) {
            hookData.cell.styles.textColor = BRAND_COLOR;
            hookData.cell.styles.fontStyle = "bold";
          }
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ── Keyword Summary (detailed) ──
  if (data.keywordSummary.length > 0) {
    y = checkPageBreak(doc, y, 50);
    y = addSectionTitle(doc, t("Детали по ключевым словам", "Keyword Details", lang), y);

    // Build model columns dynamically
    const allModels = new Set<string>();
    data.keywordSummary.forEach(ks => ks.models.forEach(m => allModels.add(m.model)));
    const modelList = Array.from(allModels);

    autoTable(doc, {
      startY: y,
      head: [[t("Ключевое слово", "Keyword", lang), t("Статус", "Status", lang), ...modelList]],
      body: data.keywordSummary.map(ks => {
        const modelMap: Record<string, string> = {};
        ks.models.forEach(m => { modelMap[m.model] = m.status; });
        return [
          ks.keyword,
          getStatusLabel(ks.mainStatus, lang),
          ...modelList.map(m => {
            const s = modelMap[m];
            if (s === "captured") return "✓";
            if (s === "displaced") return "~";
            return "—";
          }),
        ];
      }),
      theme: "plain",
      styles: { textColor: TEXT_WHITE, fillColor: DARK_BG, fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: CARD_BG, textColor: BRAND_COLOR, fontStyle: "bold", fontSize: 7 },
      alternateRowStyles: { fillColor: [20, 20, 28] },
      margin: { left: 15, right: 15 },
      columnStyles: {
        0: { cellWidth: 45 },
        1: { cellWidth: 25 },
      },
      didParseCell: (hookData: any) => {
        if (hookData.section === "body" && hookData.column.index >= 2) {
          const val = hookData.cell.raw as string;
          if (val === "✓") hookData.cell.styles.textColor = GREEN;
          else if (val === "~") hookData.cell.styles.textColor = YELLOW;
          else hookData.cell.styles.textColor = TEXT_MUTED;
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ── Legend ──
  y = checkPageBreak(doc, y, 25);
  doc.setFillColor(...CARD_BG);
  doc.roundedRect(15, y, 180, 18, 2, 2, "F");
  doc.setFontSize(7);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(t("Условные обозначения:", "Legend:", lang), 20, y + 6);
  doc.setTextColor(...GREEN);
  doc.text(t("✓ — Захвачен (бренд найден)", "✓ — Captured (brand found)", lang), 20, y + 12);
  doc.setTextColor(...YELLOW);
  doc.text(t("~ — Вытеснен (частично)", "~ — Displaced (partial)", lang), 80, y + 12);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(t("— — Не найден", "— — Not found", lang), 140, y + 12);

  // ── Footers ──
  addFooters(doc, lang);

  doc.save(`GEO_Radar_${data.brandName.replace(/\s+/g, "_")}_${data.date}.pdf`);
}

export function generateSourcesPdf(data: SourcesReportData, brandName: string, date: string, lang: string = "ru") {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  registerCyrillicFont(doc);

  doc.setFillColor(...DARK_BG);
  doc.rect(0, 0, 210, 297, "F");

  addHeader(doc, brandName, t("Отчёт по источникам ИИ", "AI Sources Report", lang), date, lang);

  let y = 50;

  y = addSectionTitle(doc, t("Обзор источников", "Sources Overview", lang), y);
  y = addKpiRow(doc, [
    { label: t("Всего источников", "Total Sources", lang), value: String(data.totalSources) },
    { label: t("Всего упоминаний", "Total Mentions", lang), value: String(data.totalOccurrences) },
    { label: t("Типов источников", "Source Types", lang), value: String(data.pieData.length) },
    { label: t("Топ источник", "Top Source", lang), value: data.sources[0]?.domain || "-" },
  ], y);

  if (data.pieData.length > 0) {
    y = checkPageBreak(doc, y, 40);
    y = addSectionTitle(doc, t("Распределение по типам", "Distribution by Type", lang), y);
    autoTable(doc, {
      startY: y,
      head: [[t("Тип", "Type", lang), t("Упоминания", "Mentions", lang), t("Доля", "Share", lang)]],
      body: data.pieData.map(d => {
        const total = data.pieData.reduce((s, x) => s + x.value, 0) || 1;
        return [d.name, String(d.value), `${Math.round((d.value / total) * 100)}%`];
      }),
      theme: "plain",
      styles: { textColor: TEXT_WHITE, fillColor: DARK_BG, fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: CARD_BG, textColor: BRAND_COLOR, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [20, 20, 28] },
      margin: { left: 15, right: 15 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  y = checkPageBreak(doc, y, 50);
  y = addSectionTitle(doc, t("Топ источники", "Top Sources", lang), y);
  const topSources = data.sources.slice(0, 30);
  autoTable(doc, {
    startY: y,
    head: [["#", t("Домен", "Domain", lang), t("Тип", "Type", lang), t("Упоминания", "Mentions", lang)]],
    body: topSources.map((s, i) => [String(i + 1), s.domain, s.typeLabel, String(s.occurrenceCount)]),
    theme: "plain",
    styles: { textColor: TEXT_WHITE, fillColor: DARK_BG, fontSize: 8, cellPadding: 2.5 },
    headStyles: { fillColor: CARD_BG, textColor: BRAND_COLOR, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [20, 20, 28] },
    margin: { left: 15, right: 15 },
  });

  addFooters(doc, lang);

  doc.save(`AI_Sources_${brandName.replace(/\s+/g, "_")}_${date}.pdf`);
}
