import { applyCommerceLayer } from "./commercePages.ts";
const silos=[{id:"s-1",name:"Крепеж",slug:"krepezh",description:"Раздел",position:0}] as any;
const clusters=[{id:"c-1",silo_id:"s-1",parent_id:null,name:"Болты",slug:"bolty",description:"Категория",position:0,page_type:"category"}] as any;
const products=Array.from({length:6},(_,i)=>({id:`p-${i+1}`,silo_id:"s-1",site_cluster_id:"c-1",sku:`SKU-${i+1}`,name:`Болт M${i+6}`,slug:null,url_path:null,price:100+i,currency:"RUB",brand:"Acme",availability:"InStock",description:"Описание.",characteristics:{"Диаметр":`M${i+6}`},images:null,kind:"product",status:"active",position:i})) as any;
const chrome:any={domain:"example.com",siteName:"Море болтов",siteAbout:"Крепеж",topic:"крепеж",lang:"ru",accent:"#6E56CF",headingFont:"Inter",bodyFont:"Inter",projectId:"proj-3d"};
const a=applyCommerceLayer({chrome,files:{"index.html":"<html></html>"},silos,clusters,products});
const b=applyCommerceLayer({chrome,files:{"index.html":"<html></html>"},silos,clusters,products});
console.log("KEYS",Object.keys(a.files));
console.log("PATHS",a.extraPaths);
console.log("DETERM",Object.keys(a.files).filter(k=>a.files[k]!==b.files[k]));
