
INSERT INTO public.document_types (
  slug, name, description, category, target_length_words, target_pages,
  primary_model, fallback_model, ui_priority, preferred_distribution_platforms,
  anchors_config, client_pages_config, reference_source_config,
  generation_pattern, system_prompt_template, post_checks_config,
  pdf_template_config, html_landing_config, is_active
) VALUES
(
  'ranking', 'Рейтинг лучших',
  'Топ-10 продуктов или услуг с обоснованием критериев рейтинга. 8-15 стр. Флагман для запросов «лучший X 2026», «топ X для Y». Требует источник — каталог продуктов клиента.',
  'pdf', '{"min":1500,"max":2800}'::jsonb, '{"min":8,"max":15}'::jsonb,
  'google/gemini-2.5-pro', 'google/gemini-2.5-flash', 45, '["github_pages"]'::jsonb,
  '{"count_min":1,"count_max":2,"placement":"body"}'::jsonb,
  '{"count_min":3,"count_max":6,"placement_rules":"by_h2"}'::jsonb,
  '{"required":true,"recommended":true,"source_types_allowed":["client_page","client_pages_list"],"min_source_word_count":200,"fallback_behavior":"fail_generation"}'::jsonb,
  'inline',
  E'Ты редактор рейтингов. Собираешь честный топ на основе данных клиента.\n\n## Контекст клиента\nБренд: {{client.name}}\nДомен: https://{{client.domain}}\nЭксперт-автор: {{client.expert_name}}\nТональность: {{client.brand_voice}}\n\n## КРИТИЧЕСКИЙ ЗАПРЕТ\nВсе позиции рейтинга берутся СТРОГО из блока источников клиента. Категорически запрещено выдумывать названия моделей, брендов, продуктов и их индексы. Если данных мало - раскрывай глубже те позиции, что есть в источнике.\n\n## ЖЁСТКИЕ ТРЕБОВАНИЯ К СТРУКТУРЕ\n- H1 заголовок рейтинга\n- Введение: методология оценки, 2-3 абзаца\n- `## Критерии оценки` - список из 4-6 критериев\n- `## Топ-10` - внутри ровно 10 позиций формата `### N. Название`\n- Каждая позиция: 2-3 предложения обоснования, затем 3-5 bullet-характеристик, затем строки `Плюсы:` и `Минусы:`\n- Порядок обоснован: для позиции 1 объясни, почему именно она первая, а не «просто первая»\n- Финальный блок `## Как выбрать из топа?` - 3-5 практических советов\n\nПроверь перед выдачей:\n1. Ровно 10 H3-позиций внутри `## Топ-10`?\n2. Все названия встречаются в источнике клиента?\n3. Есть `## Критерии оценки` и `## Как выбрать из топа?`?\n4. Объём 1500-2800 слов?\n\n## Обязательный шаблон\n\n# Топ-10 [категория]: рейтинг {{year}}\n\nВведение с методологией.\n\n## Критерии оценки\n- Критерий 1 - пояснение\n- Критерий 2 - пояснение\n\n## Топ-10\n\n### 1. [Название из источника]\nОбоснование 2-3 предложения.\n- Характеристика\n- Характеристика\nПлюсы: ...\nМинусы: ...\n\n### 2. [Название из источника]\n...\n\n## Как выбрать из топа?\n- Совет 1\n- Совет 2\n\n## Ссылки на клиента\n{{anchors_block}}\n{{client_pages_block}}\n\n## Формат ответа\nТолько markdown. Начинай с `# `, заканчивай разделом `## Как выбрать из топа?`.',
  '[
    {"type":"h1_present"},
    {"type":"min_word_count","min":1400},
    {"type":"max_word_count","max":3000},
    {"type":"ranking_items_count","min":10,"max":12,"section":"Топ-10"},
    {"type":"use_source_facts","minSourceReferences":8},
    {"type":"final_section_exact","title":"Как выбрать из топа?"},
    {"type":"no_forbidden_openings","phrases":["в этом рейтинге","в этой статье","как известно","многие задаются вопросом"]},
    {"type":"no_invented_brands"},
    {"type":"no_metadata_leak"},
    {"type":"context_links_count","min":4,"max":8}
  ]'::jsonb,
  '{"version":"1.0","structure":[
    {"block":"cover","elements":["logo","h1_title","subtitle","banner_from_unsplash"],"subtitle":"Рейтинг 2026"},
    {"block":"criteria_box","title":"Критерии оценки"},
    {"block":"ranking_items","section":"Топ-10"},
    {"block":"final_advice_section","title":"Как выбрать из топа?"},
    {"block":"author_card_full"},
    {"block":"cta_button","text":"Подобрать вместе с экспертом","utm_content":"cta_ranking"},
    {"block":"brand_footer_pagination","left_content":"{{expert_name}}, {{brand_name}}","right_content":"{{domain}}"}
  ]}'::jsonb,
  '{"schema_type":"ItemList","structured_data_ranking_items":true,"hero_image":true,"content_placement":"full","cta_placement":"top_and_bottom","download_button_text":"Скачать рейтинг в PDF","ranking_section":"Топ-10"}'::jsonb,
  true
),
(
  'comparison_review', 'Сравнительный обзор',
  '3-5 альтернатив по критериям с таблицей сравнения. 10-18 стр. Для запросов «X vs Y», «сравнение X». Требует источники для каждой альтернативы.',
  'pdf', '{"min":2000,"max":3500}'::jsonb, '{"min":10,"max":18}'::jsonb,
  'google/gemini-2.5-pro', 'google/gemini-2.5-flash', 40, '["github_pages"]'::jsonb,
  '{"count_min":1,"count_max":2,"placement":"body"}'::jsonb,
  '{"count_min":4,"count_max":8,"placement_rules":"by_h2"}'::jsonb,
  '{"required":true,"recommended":true,"source_types_allowed":["client_pages_list"],"min_source_word_count":400,"fallback_behavior":"fail_generation","min_sources_count":2,"max_sources_count":5}'::jsonb,
  'background',
  E'Ты аналитик-обозреватель. Готовишь честное сравнение альтернатив по данным клиента.\n\n## Контекст клиента\nБренд: {{client.name}}\nДомен: https://{{client.domain}}\nЭксперт-автор: {{client.expert_name}}\nТональность: {{client.brand_voice}}\n\n## КРИТИЧЕСКИЙ ЗАПРЕТ\nСравниваются ТОЛЬКО те альтернативы, которые есть в источниках клиента. Не выдумывай названия моделей, брендов и их числовые индексы.\n\n## ЖЁСТКИЕ ТРЕБОВАНИЯ К СТРУКТУРЕ\n- H1 заголовок сравнения\n- Введение 2-3 абзаца\n- `## Критерии сравнения` - список 5-7 критериев\n- `## Общая таблица` - markdown-таблица: колонки = альтернативы, строки = критерии (минимум 4 строки и 3 колонки)\n- `## Разбор альтернатив` - внутри 3-5 H3, по одному на альтернативу\n- Каждый разбор: 200-300 слов, строки `Плюсы:` и `Минусы:`, абзац «Кому подойдёт»\n- `## Рекомендация по выбору` - конкретика формата «Если вам важно X - выбирайте Y»\n\nПроверь перед выдачей:\n1. Таблица в `## Общая таблица` не меньше 4x3?\n2. От 3 до 5 H3 в `## Разбор альтернатив`?\n3. Есть `## Рекомендация по выбору`?\n4. Объём 2000-3500 слов?\n\n## Обязательный шаблон\n\n# [A] vs [B]: сравнительный обзор\n\nВведение.\n\n## Критерии сравнения\n- Критерий - зачем он важен\n\n## Общая таблица\n\n| Критерий | Альтернатива A | Альтернатива B |\n| --- | --- | --- |\n| Цена | ... | ... |\n| Характеристики | ... | ... |\n| Кому подходит | ... | ... |\n\n## Разбор альтернатив\n\n### [Альтернатива A]\nРазбор 200-300 слов.\nПлюсы: ...\nМинусы: ...\nКому подойдёт: ...\n\n### [Альтернатива B]\n...\n\n## Рекомендация по выбору\nЕсли вам важно X - выбирайте Y.\n\n## Ссылки на клиента\n{{anchors_block}}\n{{client_pages_block}}\n\n## Формат ответа\nТолько markdown. Начинай с `# `, заканчивай разделом `## Рекомендация по выбору`.',
  '[
    {"type":"h1_present"},
    {"type":"min_word_count","min":1900},
    {"type":"max_word_count","max":3700},
    {"type":"comparison_table_present","min_rows":4,"min_cols":3},
    {"type":"alternatives_count_between","min":3,"max":5,"section":"Разбор альтернатив"},
    {"type":"use_source_facts","minSourceReferences":3},
    {"type":"final_section_exact","title":"Рекомендация по выбору"},
    {"type":"no_forbidden_openings","phrases":["в этом обзоре","в этой статье","как известно","стоит отметить"]},
    {"type":"no_invented_brands"},
    {"type":"no_metadata_leak"},
    {"type":"context_links_count","min":5,"max":9}
  ]'::jsonb,
  '{"version":"1.0","structure":[
    {"block":"cover","elements":["logo","h1_title","subtitle","banner_from_unsplash"],"subtitle":"Vs-сравнение 2026"},
    {"block":"criteria_list","title":"Критерии сравнения"},
    {"block":"comparison_table_main","title":"Общая таблица"},
    {"block":"alternative_sections","section":"Разбор альтернатив"},
    {"block":"recommendation_final","title":"Рекомендация по выбору"},
    {"block":"author_card_full"},
    {"block":"cta_button","text":"Обсудить выбор с экспертом","utm_content":"cta_comparison"},
    {"block":"brand_footer_pagination","left_content":"{{expert_name}}, {{brand_name}}","right_content":"{{domain}}"}
  ]}'::jsonb,
  '{"schema_type":"Article","article_section":"Comparison","hero_image":true,"content_placement":"full","prominent_download_button":true,"cta_placement":"top_and_bottom","download_button_text":"Скачать сравнение в PDF"}'::jsonb,
  true
),
(
  'glossary', 'Глоссарий терминов',
  'Алфавитный справочник ключевых терминов по теме. 8-16 стр. Мощная SEO-фича для длинного хвоста запросов «что такое X». Может работать без источника - модель знает термины отрасли.',
  'pdf', '{"min":1500,"max":3000}'::jsonb, '{"min":8,"max":16}'::jsonb,
  'google/gemini-2.5-flash', 'google/gemini-2.5-pro', 35, '["github_pages"]'::jsonb,
  '{"count_min":1,"count_max":2,"placement":"body"}'::jsonb,
  '{"count_min":3,"count_max":6,"placement_rules":"anywhere"}'::jsonb,
  '{"required":false,"recommended":true,"source_types_allowed":["client_page","external_url"],"min_source_word_count":100,"fallback_behavior":"skip_if_missing"}'::jsonb,
  'inline',
  E'Ты составитель отраслевого глоссария.\n\n## Контекст клиента\nБренд: {{client.name}}\nДомен: https://{{client.domain}}\nЭксперт-автор: {{client.expert_name}}\nТональность: {{client.brand_voice}}\n\n## ЖЁСТКИЕ ТРЕБОВАНИЯ К СТРУКТУРЕ\n- H1 заголовок глоссария\n- Введение: для кого этот справочник, 1-2 абзаца\n- Алфавитные разделы: `## А`, `## Б`, `## В` и так далее, СТРОГО по алфавиту\n- Внутри каждой буквы термины как `### Термин`\n- Всего 25-40 терминов\n- Каждое определение 40-80 слов, плюс пример использования или синонимы\n- Если указан источник клиента - объясняй в первую очередь термины из него\n- Финальный раздел `## См. также` - 5-7 связанных тем\n\nПроверь перед выдачей:\n1. Не меньше 25 H3-терминов?\n2. H2-буквы идут по алфавиту без нарушений?\n3. Каждое определение не короче 40 слов?\n4. Есть `## См. также`?\n\n## Обязательный шаблон\n\n# Глоссарий: [тема]\n\nВведение.\n\n## А\n\n### Термин\nОпределение 40-80 слов. Пример использования.\n\n## Б\n\n### Термин\n...\n\n## См. также\n- Связанная тема\n\n## Ссылки на клиента\n{{anchors_block}}\n{{client_pages_block}}\n\n## Формат ответа\nТолько markdown. Начинай с `# `, заканчивай разделом `## См. также`.',
  '[
    {"type":"h1_present"},
    {"type":"min_word_count","min":1400},
    {"type":"max_word_count","max":3200},
    {"type":"glossary_terms_count","min":25,"max":60},
    {"type":"alphabetical_order"},
    {"type":"min_definition_length","min":40},
    {"type":"final_section_exact","title":"См. также"},
    {"type":"no_forbidden_openings","phrases":["в этом глоссарии","в этой статье","как известно"]},
    {"type":"no_metadata_leak"}
  ]'::jsonb,
  '{"version":"1.0","structure":[
    {"block":"cover","elements":["logo","h1_title","subtitle"],"subtitle":"Справочник терминов"},
    {"block":"glossary_toc","title":"Алфавитный указатель"},
    {"block":"glossary_letter_sections"},
    {"block":"see_also_section","title":"См. также"},
    {"block":"author_card_full"},
    {"block":"brand_footer_pagination","left_content":"{{expert_name}}, {{brand_name}}","right_content":"{{domain}}"}
  ]}'::jsonb,
  '{"schema_type":"DefinedTermSet","structured_data_glossary_items":true,"hero_image":false,"content_placement":"full","cta_placement":"bottom","download_button_text":"Скачать глоссарий в PDF"}'::jsonb,
  true
),
(
  'encyclopedia', 'Энциклопедия темы',
  'Глубокий структурированный справочник с гнёздами подтем. 12-22 стр. Отличается от глоссария - не термины, а темы и подтемы с иерархией.',
  'pdf', '{"min":2500,"max":4500}'::jsonb, '{"min":12,"max":22}'::jsonb,
  'google/gemini-2.5-pro', 'google/gemini-2.5-flash', 30, '["github_pages","archive_org"]'::jsonb,
  '{"count_min":2,"count_max":3,"placement":"body"}'::jsonb,
  '{"count_min":4,"count_max":8,"placement_rules":"by_h2"}'::jsonb,
  '{"required":false,"recommended":true,"source_types_allowed":["client_page","external_url","client_pages_list"],"min_source_word_count":200,"fallback_behavior":"skip_if_missing"}'::jsonb,
  'background',
  E'Ты редактор отраслевой энциклопедии. Строишь иерархический справочник по теме.\n\n## Контекст клиента\nБренд: {{client.name}}\nДомен: https://{{client.domain}}\nЭксперт-автор: {{client.expert_name}}\nТональность: {{client.brand_voice}}\n\n## КРИТИЧЕСКИЙ ЗАПРЕТ\nНе выдумывай названия моделей, брендов и числовые индексы техники, которых нет в источнике.\n\n## ЖЁСТКИЕ ТРЕБОВАНИЯ К СТРУКТУРЕ\n- H1 заголовок энциклопедии\n- Введение `Что охватывает эта энциклопедия` - 2-3 абзаца\n- 6-9 крупных H2-разделов\n- Внутри разделов H3-подтемы, всего не меньше 15 подтем\n- Каждая H3-подтема: 100-200 слов\n- Кросс-ссылки между разделами: строка «См. также раздел X»\n- `## Ключевые понятия` - опорные термины\n- Финальный раздел `## Дальнейшее изучение` - 5-10 пунктов для углубления\n\nПроверь перед выдачей:\n1. От 6 до 9 H2-разделов (без учёта финального)?\n2. Не меньше 15 H3-подтем?\n3. Есть `## Дальнейшее изучение`?\n4. Объём 2500-4500 слов?\n\n## Обязательный шаблон\n\n# Энциклопедия: [тема]\n\n## Что охватывает эта энциклопедия\nВведение.\n\n## [Раздел 1]\n\n### [Подтема]\n100-200 слов.\nСм. также раздел [Раздел 3].\n\n## [Раздел 2]\n### [Подтема]\n...\n\n## Ключевые понятия\n- Понятие - пояснение\n\n## Дальнейшее изучение\n- Направление для углубления\n\n## Ссылки на клиента\n{{anchors_block}}\n{{client_pages_block}}\n\n## Формат ответа\nТолько markdown. Начинай с `# `, заканчивай разделом `## Дальнейшее изучение`.',
  '[
    {"type":"h1_present"},
    {"type":"min_word_count","min":2400},
    {"type":"max_word_count","max":4700},
    {"type":"h2_count","min":6,"max":10},
    {"type":"h3_count","min":15},
    {"type":"final_section_exact","title":"Дальнейшее изучение"},
    {"type":"no_forbidden_openings","phrases":["в этой энциклопедии","в этой статье","как известно"]},
    {"type":"no_metadata_leak"},
    {"type":"context_links_count","min":6,"max":11}
  ]'::jsonb,
  '{"version":"1.0","structure":[
    {"block":"cover_expert","elements":["logo","h1_title","banner_from_unsplash"]},
    {"block":"encyclopedia_toc","title":"Содержание"},
    {"block":"encyclopedia_sections"},
    {"block":"further_reading_box","title":"Дальнейшее изучение"},
    {"block":"author_card_full"},
    {"block":"cta_button","text":"Задать вопрос эксперту","utm_content":"cta_encyclopedia"},
    {"block":"back_cover"},
    {"block":"brand_footer_pagination","left_content":"{{expert_name}}, {{brand_name}}","right_content":"{{domain}}"}
  ]}'::jsonb,
  '{"schema_type":"Article","article_section":"Encyclopedia","hero_image":true,"content_placement":"excerpt_with_download","excerpt_paragraphs":3,"excerpt_show_toc":true,"prominent_download_button":true,"download_button_size":"extra_large","download_button_text":"Скачать энциклопедию (PDF)","cta_placement":"bottom"}'::jsonb,
  true
),
(
  'mistakes', 'Ошибки покупателей',
  'Типичные ошибки при покупке или выборе X плюс способы их избежать. 8-14 стр. Для запросов «X ошибок при покупке», «на что обратить внимание». Работает без источника - экспертный опыт клиента.',
  'pdf', '{"min":1500,"max":2500}'::jsonb, '{"min":8,"max":14}'::jsonb,
  'google/gemini-2.5-flash', 'google/gemini-2.5-pro', 50, '["github_pages","linkedin_publisher"]'::jsonb,
  '{"count_min":1,"count_max":2,"placement":"body"}'::jsonb,
  '{"count_min":2,"count_max":4,"placement_rules":"by_h2"}'::jsonb,
  '{"required":false,"recommended":false,"source_types_allowed":["client_page"],"min_source_word_count":100,"fallback_behavior":"skip_if_missing"}'::jsonb,
  'inline',
  E'Ты практикующий эксперт. Разбираешь типичные ошибки покупателей.\n\n## Контекст клиента\nБренд: {{client.name}}\nДомен: https://{{client.domain}}\nЭксперт-автор: {{client.expert_name}}\nТональность: {{client.brand_voice}}\n\n## КРИТИЧЕСКИЙ ЗАПРЕТ\nНе выдумывай названия моделей, брендов и числовые индексы техники, которых нет в источнике.\n\n## ЖЁСТКИЕ ТРЕБОВАНИЯ К СТРУКТУРЕ\n- H1 вида `N ошибок при выборе [объект]`\n- Введение 1-2 абзаца\n- От 8 до 12 H2-разделов СТРОГО в формате `## Ошибка N: Название`\n- Каждая ошибка: что делают неправильно (100-150 слов), почему это плохо, затем строка `Как избежать:` с конкретным советом\n- Стиль экспертный, с примерами из практики, без выдуманных компаний и людей\n- Финальный раздел `## Итоговый чек-лист безопасной покупки` - 5-7 пунктов списком\n\nПроверь перед выдачей:\n1. От 8 до 12 H2 вида `## Ошибка N: ...`?\n2. У каждой ошибки есть `Как избежать:`?\n3. Есть `## Итоговый чек-лист безопасной покупки` с 5-7 пунктами?\n4. Объём 1500-2500 слов?\n\n## Обязательный шаблон\n\n# 10 ошибок при выборе [объект]\n\nВведение.\n\n## Ошибка 1: [Название]\nЧто делают неправильно, 100-150 слов. Почему это плохо.\nКак избежать: конкретный совет.\n\n## Ошибка 2: [Название]\n...\n\n## Итоговый чек-лист безопасной покупки\n- Пункт 1\n- Пункт 2\n\n## Ссылки на клиента\n{{anchors_block}}\n{{client_pages_block}}\n\n## Формат ответа\nТолько markdown. Начинай с `# `, заканчивай разделом `## Итоговый чек-лист безопасной покупки`.',
  '[
    {"type":"h1_present"},
    {"type":"min_word_count","min":1400},
    {"type":"max_word_count","max":2700},
    {"type":"mistakes_count","min":8,"max":12},
    {"type":"final_section_exact","title":"Итоговый чек-лист безопасной покупки"},
    {"type":"no_forbidden_openings","phrases":["в этой статье","в этом документе","как известно","многие задаются вопросом"]},
    {"type":"no_invented_brands"},
    {"type":"no_metadata_leak"},
    {"type":"context_links_count","min":3,"max":6}
  ]'::jsonb,
  '{"version":"1.0","structure":[
    {"block":"cover","elements":["logo","h1_title","banner_from_unsplash"]},
    {"block":"intro_paragraph"},
    {"block":"mistake_items","pattern":"^Ошибка\\\\s*\\\\d+"},
    {"block":"final_checklist_box","title":"Итоговый чек-лист безопасной покупки"},
    {"block":"author_card_full"},
    {"block":"cta_button","text":"Проверить свой выбор с экспертом","utm_content":"cta_mistakes"},
    {"block":"brand_footer_pagination","left_content":"{{expert_name}}, {{brand_name}}","right_content":"{{domain}}"}
  ]}'::jsonb,
  '{"schema_type":"Article","article_section":"Warning","hero_image":true,"content_placement":"full","cta_placement":"top_and_bottom","download_button_text":"Скачать разбор ошибок в PDF"}'::jsonb,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  target_length_words = EXCLUDED.target_length_words,
  target_pages = EXCLUDED.target_pages,
  primary_model = EXCLUDED.primary_model,
  fallback_model = EXCLUDED.fallback_model,
  ui_priority = EXCLUDED.ui_priority,
  preferred_distribution_platforms = EXCLUDED.preferred_distribution_platforms,
  anchors_config = EXCLUDED.anchors_config,
  client_pages_config = EXCLUDED.client_pages_config,
  reference_source_config = EXCLUDED.reference_source_config,
  generation_pattern = EXCLUDED.generation_pattern,
  system_prompt_template = EXCLUDED.system_prompt_template,
  post_checks_config = EXCLUDED.post_checks_config,
  pdf_template_config = EXCLUDED.pdf_template_config,
  html_landing_config = EXCLUDED.html_landing_config,
  is_active = true,
  updated_at = now();
