
-- Table for PBN site templates
CREATE TABLE public.pbn_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_key text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  html_structure text NOT NULL,
  css_styles text NOT NULL DEFAULT '',
  font_pairs jsonb NOT NULL DEFAULT '[["Inter","Inter"]]'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  is_builtin boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.pbn_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can view active templates"
  ON public.pbn_templates FOR SELECT
  TO authenticated
  USING (is_active = true OR has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins manage templates"
  ON public.pbn_templates FOR ALL
  TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE TRIGGER pbn_templates_updated_at
  BEFORE UPDATE ON public.pbn_templates
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Seed 8 templates
INSERT INTO public.pbn_templates (template_key, name, description, font_pairs, is_builtin, sort_order, html_structure, css_styles) VALUES
('corporate', 'Корпоратив', 'Строгий синий, sans-serif, корпоративный стиль', '[["Inter","Inter"],["IBM Plex Sans","IBM Plex Sans"]]'::jsonb, true, 1,
$HTML$<!doctype html><html lang="{{lang}}"><head><meta charset="utf-8"><title>{{title}}</title><meta name="description" content="{{description}}"><link rel="stylesheet" href="/style.css"><link href="https://fonts.googleapis.com/css2?family={{heading_font_url}}:wght@400;700&family={{body_font_url}}:wght@400;600&display=swap" rel="stylesheet"></head><body><header class="corp-header"><div class="container"><div class="logo">{{site_name}}</div><nav><a href="/">Главная</a><a href="/about.html">О компании</a><a href="/contacts.html">Контакты</a></nav></div></header><main class="container"><section class="hero"><h1>{{site_name}}</h1><p class="lede">{{site_about}}</p></section><section class="entries">{{#posts}}<article class="entry"><h2><a href="{{url}}">{{title}}</a></h2><p>{{excerpt}}</p></article>{{/posts}}</section></main><footer class="corp-footer"><div class="container"><p>© {{year}} {{site_name}}. Все права защищены.</p></div></footer></body></html>$HTML$,
$CSS$:root{--accent:{{accent}};--bg:#f5f7fb;--ink:#0f172a;--muted:#475569}*{box-sizing:border-box}body{margin:0;font-family:'{{body_font}}',sans-serif;background:var(--bg);color:var(--ink);line-height:1.6}.container{max-width:1100px;margin:0 auto;padding:0 24px}.corp-header{background:#fff;border-bottom:2px solid var(--accent);padding:18px 0}.corp-header .container{display:flex;justify-content:space-between;align-items:center}.logo{font-family:'{{heading_font}}';font-weight:700;font-size:22px;color:var(--accent)}nav a{margin-left:24px;color:var(--ink);text-decoration:none;font-weight:600}nav a:hover{color:var(--accent)}.hero{padding:64px 0 32px}h1{font-family:'{{heading_font}}';font-size:42px;margin:0 0 12px;color:var(--accent)}.lede{color:var(--muted);font-size:18px}.entries{display:grid;gap:20px;padding:24px 0 60px}.entry{background:#fff;padding:24px;border-left:4px solid var(--accent);border-radius:4px}.entry h2{margin:0 0 8px;font-family:'{{heading_font}}'}.entry a{color:var(--ink);text-decoration:none}.entry a:hover{color:var(--accent)}.corp-footer{background:#0f172a;color:#cbd5e1;padding:24px 0}$CSS$),

('minimal', 'Минимал', 'Белый фон, много воздуха, тонкие линии, serif', '[["Lora","Inter"],["Playfair Display","Source Sans 3"],["EB Garamond","Nunito"]]'::jsonb, true, 2,
$HTML$<!doctype html><html lang="{{lang}}"><head><meta charset="utf-8"><title>{{title}}</title><meta name="description" content="{{description}}"><link rel="stylesheet" href="/style.css"><link href="https://fonts.googleapis.com/css2?family={{heading_font_url}}:wght@400;700&family={{body_font_url}}:wght@400&display=swap" rel="stylesheet"></head><body><main class="wrap"><header class="m-head"><a href="/" class="brand">{{site_name}}</a><nav><a href="/">Дом</a><a href="/about.html">О сайте</a></nav></header><section class="intro"><h1>{{site_name}}</h1><p>{{site_about}}</p></section><section class="posts">{{#posts}}<article class="post"><h2><a href="{{url}}">{{title}}</a></h2><p>{{excerpt}}</p><a class="more" href="{{url}}">Читать →</a></article>{{/posts}}</section><footer class="m-foot"><p>{{year}} · {{site_name}}</p></footer></main></body></html>$HTML$,
$CSS$:root{--accent:{{accent}};--ink:#1a1a1a;--line:#e8e8e8}*{box-sizing:border-box}body{margin:0;background:#fff;color:var(--ink);font-family:'{{body_font}}',serif;line-height:1.7}.wrap{max-width:680px;margin:0 auto;padding:60px 24px}.m-head{display:flex;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:24px}.brand{font-family:'{{heading_font}}';font-size:20px;color:var(--ink);text-decoration:none}nav a{margin-left:20px;color:#666;text-decoration:none;font-size:14px}nav a:hover{color:var(--accent)}.intro{padding:80px 0 60px;text-align:center}h1{font-family:'{{heading_font}}';font-weight:400;font-size:48px;margin:0 0 16px}.posts{display:flex;flex-direction:column;gap:48px}.post{border-bottom:1px solid var(--line);padding-bottom:48px}.post h2{font-family:'{{heading_font}}';font-weight:400;margin:0 0 12px}.post a{color:var(--ink);text-decoration:none}.post a:hover{color:var(--accent)}.more{display:inline-block;margin-top:12px;font-size:14px;color:var(--accent)}.m-foot{margin-top:80px;text-align:center;color:#999;font-size:13px}$CSS$),

('magazine', 'Журнал', 'Двухколоночная сетка, карточки, яркие теги', '[["DM Sans","DM Sans"],["Manrope","Manrope"],["Plus Jakarta Sans","Plus Jakarta Sans"]]'::jsonb, true, 3,
$HTML$<!doctype html><html lang="{{lang}}"><head><meta charset="utf-8"><title>{{title}}</title><meta name="description" content="{{description}}"><link rel="stylesheet" href="/style.css"><link href="https://fonts.googleapis.com/css2?family={{heading_font_url}}:wght@400;700;800&display=swap" rel="stylesheet"></head><body><header class="mag-top"><div class="row"><a class="mag-brand" href="/">{{site_name}}</a><nav><a href="/">Главная</a><a href="/about.html">Редакция</a><a href="/contacts.html">Контакты</a></nav></div></header><main class="row"><section class="grid">{{#posts}}<article class="card"><span class="tag">статья</span><h2><a href="{{url}}">{{title}}</a></h2><p>{{excerpt}}</p></article>{{/posts}}</section></main><footer class="mag-foot"><div class="row"><p>© {{year}} {{site_name}} · {{site_about}}</p></div></footer></body></html>$HTML$,
$CSS$:root{--accent:{{accent}};--bg:#fafafa;--ink:#111}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:'{{body_font}}',sans-serif;line-height:1.55}.row{max-width:1200px;margin:0 auto;padding:0 24px}.mag-top{background:#fff;border-bottom:3px solid var(--accent);padding:20px 0}.mag-top .row{display:flex;justify-content:space-between;align-items:center}.mag-brand{font-family:'{{heading_font}}';font-weight:800;font-size:26px;color:var(--accent);text-decoration:none;letter-spacing:-.5px}nav a{margin-left:22px;color:var(--ink);text-decoration:none;font-weight:600;font-size:14px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:24px;padding:40px 0}@media(max-width:720px){.grid{grid-template-columns:1fr}}.card{background:#fff;padding:24px;border-radius:12px;box-shadow:0 4px 18px rgba(0,0,0,.06)}.tag{display:inline-block;background:var(--accent);color:#fff;font-size:11px;text-transform:uppercase;padding:4px 10px;border-radius:99px;font-weight:700;letter-spacing:.5px}.card h2{font-family:'{{heading_font}}';margin:12px 0 8px}.card a{color:var(--ink);text-decoration:none}.card a:hover{color:var(--accent)}.mag-foot{margin-top:40px;background:#111;color:#aaa;padding:32px 0}$CSS$),

('news', 'Новости', 'Плотная сетка 3 колонки, компактный sans-serif', '[["Roboto","Roboto"],["IBM Plex Sans","IBM Plex Sans"],["Open Sans","Open Sans"]]'::jsonb, true, 4,
$HTML$<!doctype html><html lang="{{lang}}"><head><meta charset="utf-8"><title>{{title}}</title><meta name="description" content="{{description}}"><link rel="stylesheet" href="/style.css"><link href="https://fonts.googleapis.com/css2?family={{heading_font_url}}:wght@400;700&display=swap" rel="stylesheet"></head><body><div class="news-bar"><div class="ncont"><strong>{{site_name}}</strong><nav><a href="/">Лента</a><a href="/about.html">О редакции</a><a href="/contacts.html">Контакты</a></nav></div></div><main class="ncont"><h1 class="news-h1">{{site_name}}</h1><p class="news-sub">{{site_about}}</p><ul class="news-list">{{#posts}}<li class="item"><h3><a href="{{url}}">{{title}}</a></h3><p>{{excerpt}}</p><time>{{date}}</time></li>{{/posts}}</ul></main><footer class="news-foot"><div class="ncont"><span>© {{year}} {{site_name}}</span></div></footer></body></html>$HTML$,
$CSS$:root{--accent:{{accent}};--ink:#222;--mute:#666;--line:#ddd}*{box-sizing:border-box}body{margin:0;background:#f4f4f4;color:var(--ink);font-family:'{{body_font}}',sans-serif;font-size:15px;line-height:1.5}.ncont{max-width:1240px;margin:0 auto;padding:0 16px}.news-bar{background:var(--accent);color:#fff;padding:8px 0;font-size:13px}.news-bar .ncont{display:flex;justify-content:space-between;align-items:center}.news-bar nav a{color:#fff;text-decoration:none;margin-left:18px;opacity:.9}.news-h1{font-family:'{{heading_font}}';font-size:30px;margin:24px 0 4px}.news-sub{color:var(--mute);margin:0 0 20px}.news-list{list-style:none;padding:0;margin:0;display:grid;grid-template-columns:repeat(3,1fr);gap:16px}@media(max-width:900px){.news-list{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.news-list{grid-template-columns:1fr}}.item{background:#fff;padding:14px;border-top:3px solid var(--accent)}.item h3{margin:0 0 6px;font-family:'{{heading_font}}';font-size:17px}.item a{color:var(--ink);text-decoration:none}.item a:hover{color:var(--accent)}.item time{color:var(--mute);font-size:12px}.news-foot{margin-top:30px;background:#222;color:#bbb;padding:18px 0;font-size:13px}$CSS$),

('landing', 'Лендинг', 'Hero с градиентом, CTA кнопки', '[["Outfit","Inter"],["Sora","Manrope"],["Space Grotesk","DM Sans"]]'::jsonb, true, 5,
$HTML$<!doctype html><html lang="{{lang}}"><head><meta charset="utf-8"><title>{{title}}</title><meta name="description" content="{{description}}"><link rel="stylesheet" href="/style.css"><link href="https://fonts.googleapis.com/css2?family={{heading_font_url}}:wght@400;700;800&family={{body_font_url}}:wght@400;600&display=swap" rel="stylesheet"></head><body><header class="hero"><nav class="lnav"><a class="lbrand" href="/">{{site_name}}</a><div><a href="/about.html">О нас</a><a href="/contacts.html">Контакты</a></div></nav><div class="hbox"><h1>{{site_name}}</h1><p class="hsub">{{site_about}}</p><a class="cta" href="#blocks">Узнать больше</a></div></header><section id="blocks" class="blocks"><div class="bwrap">{{#posts}}<div class="block"><h2><a href="{{url}}">{{title}}</a></h2><p>{{excerpt}}</p><a class="link" href="{{url}}">Подробнее</a></div>{{/posts}}</div></section><footer class="lfoot"><p>© {{year}} {{site_name}}</p></footer></body></html>$HTML$,
$CSS$:root{--accent:{{accent}}}*{box-sizing:border-box}body{margin:0;font-family:'{{body_font}}',sans-serif;color:#0f172a;line-height:1.6;background:#fff}.hero{background:linear-gradient(135deg,var(--accent),#0f172a);color:#fff;padding:0 24px 80px}.lnav{display:flex;justify-content:space-between;padding:24px 0;max-width:1200px;margin:0 auto}.lbrand{font-family:'{{heading_font}}';font-weight:800;font-size:24px;color:#fff;text-decoration:none}.lnav a{color:#fff;text-decoration:none;margin-left:20px;opacity:.9}.hbox{max-width:900px;margin:0 auto;padding:80px 0;text-align:center}h1{font-family:'{{heading_font}}';font-size:56px;font-weight:800;margin:0 0 16px;letter-spacing:-1px}.hsub{font-size:20px;opacity:.9;margin:0 0 32px}.cta{display:inline-block;background:#fff;color:var(--accent);padding:16px 36px;border-radius:99px;text-decoration:none;font-weight:700}.cta:hover{transform:translateY(-2px);box-shadow:0 10px 30px rgba(0,0,0,.2)}.blocks{padding:80px 24px;background:#f8fafc}.bwrap{max-width:1200px;margin:0 auto;display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:24px}.block{background:#fff;padding:32px;border-radius:16px;box-shadow:0 6px 24px rgba(0,0,0,.06)}.block h2{font-family:'{{heading_font}}';margin:0 0 12px}.block a{color:#0f172a;text-decoration:none}.block a:hover{color:var(--accent)}.link{display:inline-block;margin-top:12px;color:var(--accent);font-weight:600;text-decoration:none}.lfoot{text-align:center;padding:32px;background:#0f172a;color:#94a3b8}$CSS$),

('expert', 'Эксперт', 'Тёмная тема, зелёные акценты, авторитетный стиль', '[["Merriweather","Lato"],["Lora","Inter"]]'::jsonb, true, 6,
$HTML$<!doctype html><html lang="{{lang}}"><head><meta charset="utf-8"><title>{{title}}</title><meta name="description" content="{{description}}"><link rel="stylesheet" href="/style.css"><link href="https://fonts.googleapis.com/css2?family={{heading_font_url}}:wght@400;700&family={{body_font_url}}:wght@400&display=swap" rel="stylesheet"></head><body><div class="ex-shell"><aside class="ex-side"><h1 class="ex-brand">{{site_name}}</h1><p class="ex-bio">{{site_about}}</p><nav><a href="/">Главная</a><a href="/about.html">Об эксперте</a><a href="/contacts.html">Контакты</a></nav></aside><main class="ex-main"><section class="ex-list">{{#posts}}<article class="block"><h2><a href="{{url}}">{{title}}</a></h2><p>{{excerpt}}</p><a class="rd" href="{{url}}">→ читать</a></article>{{/posts}}</section><footer class="ex-foot">© {{year}} · {{site_name}}</footer></main></div></body></html>$HTML$,
$CSS$:root{--accent:{{accent}};--bg:#0d1117;--panel:#161b22;--ink:#e6edf3;--mute:#8b949e}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:'{{body_font}}',serif;line-height:1.7}.ex-shell{display:grid;grid-template-columns:280px 1fr;min-height:100vh}@media(max-width:780px){.ex-shell{grid-template-columns:1fr}}.ex-side{background:var(--panel);padding:40px 28px;border-right:1px solid #21262d}.ex-brand{font-family:'{{heading_font}}';color:var(--accent);margin:0 0 12px;font-size:24px}.ex-bio{color:var(--mute);font-size:14px}.ex-side nav{display:flex;flex-direction:column;margin-top:24px;gap:8px}.ex-side nav a{color:var(--ink);text-decoration:none;padding:8px 12px;border-radius:6px}.ex-side nav a:hover{background:#21262d;color:var(--accent)}.ex-main{padding:48px}.ex-list{display:flex;flex-direction:column;gap:32px;max-width:760px}.block{border-bottom:1px solid #21262d;padding-bottom:32px}.block h2{font-family:'{{heading_font}}';margin:0 0 10px;color:var(--ink)}.block a{color:var(--ink);text-decoration:none}.block a:hover{color:var(--accent)}.rd{color:var(--accent);font-size:14px}.ex-foot{margin-top:60px;color:var(--mute);font-size:13px}$CSS$),

('local', 'Локальный бизнес', 'Тёплые цвета, акцент на команде и адресе', '[["Nunito","Open Sans"],["Quicksand","Nunito"]]'::jsonb, true, 7,
$HTML$<!doctype html><html lang="{{lang}}"><head><meta charset="utf-8"><title>{{title}}</title><meta name="description" content="{{description}}"><link rel="stylesheet" href="/style.css"><link href="https://fonts.googleapis.com/css2?family={{heading_font_url}}:wght@400;700&family={{body_font_url}}:wght@400;600&display=swap" rel="stylesheet"></head><body><header class="lb-top"><div class="lwrap"><div class="lb-brand">{{site_name}}</div><nav><a href="/">Главная</a><a href="/about.html">О нас</a><a href="/contacts.html">Адрес</a></nav></div></header><section class="lb-hero"><div class="lwrap"><h1>{{site_name}}</h1><p>{{site_about}}</p></div></section><main class="lwrap lb-main"><h2 class="lb-h">Полезные статьи</h2><div class="lb-grid">{{#posts}}<div class="card"><h3><a href="{{url}}">{{title}}</a></h3><p>{{excerpt}}</p></div>{{/posts}}</div></main><footer class="lb-foot"><div class="lwrap"><p>© {{year}} {{site_name}} · Работаем для вас</p></div></footer></body></html>$HTML$,
$CSS$:root{--accent:{{accent}};--cream:#fdf6ec;--brown:#5b3a1f;--soft:#fff}*{box-sizing:border-box}body{margin:0;background:var(--cream);color:var(--brown);font-family:'{{body_font}}',sans-serif;line-height:1.65}.lwrap{max-width:1100px;margin:0 auto;padding:0 24px}.lb-top{background:var(--soft);padding:18px 0;box-shadow:0 2px 12px rgba(91,58,31,.08)}.lb-top .lwrap{display:flex;justify-content:space-between;align-items:center}.lb-brand{font-family:'{{heading_font}}';font-weight:700;font-size:22px;color:var(--accent)}nav a{color:var(--brown);margin-left:20px;text-decoration:none;font-weight:600}nav a:hover{color:var(--accent)}.lb-hero{background:linear-gradient(180deg,var(--cream),#fff);padding:60px 0}h1{font-family:'{{heading_font}}';color:var(--accent);font-size:40px;margin:0 0 12px}.lb-main{padding:40px 24px 60px}.lb-h{font-family:'{{heading_font}}';color:var(--brown)}.lb-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px;margin-top:20px}.card{background:#fff;padding:22px;border-radius:14px;border:1px solid rgba(91,58,31,.08)}.card h3{font-family:'{{heading_font}}';margin:0 0 8px}.card a{color:var(--brown);text-decoration:none}.card a:hover{color:var(--accent)}.lb-foot{background:var(--brown);color:var(--cream);padding:24px 0;margin-top:40px}$CSS$),

('technical', 'Технический', 'Моноширинный шрифт, схемы, кодовый стиль', '[["JetBrains Mono","JetBrains Mono"],["Fira Code","Inter"],["IBM Plex Mono","IBM Plex Sans"]]'::jsonb, true, 8,
$HTML$<!doctype html><html lang="{{lang}}"><head><meta charset="utf-8"><title>{{title}}</title><meta name="description" content="{{description}}"><link rel="stylesheet" href="/style.css"><link href="https://fonts.googleapis.com/css2?family={{heading_font_url}}:wght@400;700&family={{body_font_url}}:wght@400&display=swap" rel="stylesheet"></head><body><header class="t-head"><div class="tcnt">$ {{site_name}} <span class="cur">_</span></div><nav><a href="/">~/index</a><a href="/about.html">~/about</a><a href="/contacts.html">~/contacts</a></nav></header><main class="tcnt"><section class="readme"><h1># {{site_name}}</h1><p>{{site_about}}</p></section><section class="docs">{{#posts}}<div class="block"><div class="meta">## {{date}}</div><h2><a href="{{url}}">{{title}}</a></h2><p>{{excerpt}}</p></div>{{/posts}}</section></main><footer class="t-foot"><div class="tcnt">// © {{year}} {{site_name}}</div></footer></body></html>$HTML$,
$CSS$:root{--accent:{{accent}};--bg:#fafafa;--ink:#111;--mute:#888;--line:#e5e5e5}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:'{{body_font}}',monospace;line-height:1.65;font-size:14.5px}.tcnt{max-width:880px;margin:0 auto;padding:0 24px}.t-head{background:#111;color:#0f0;padding:14px 0;font-family:'{{heading_font}}',monospace;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:12px}.t-head .tcnt{flex:1}.cur{animation:bl 1s steps(2) infinite}@keyframes bl{50%{opacity:0}}.t-head nav{padding-right:24px}.t-head nav a{color:var(--accent);margin-left:18px;text-decoration:none}.readme{padding:48px 0 24px;border-bottom:1px dashed var(--line)}h1{font-family:'{{heading_font}}',monospace;color:var(--accent);font-size:28px;margin:0 0 12px}.docs{display:flex;flex-direction:column;gap:24px;padding:24px 0 60px}.block{background:#fff;border:1px solid var(--line);border-left:3px solid var(--accent);padding:20px}.meta{color:var(--mute);font-size:12px;margin-bottom:6px}.block h2{font-family:'{{heading_font}}',monospace;font-size:18px;margin:0 0 8px}.block a{color:var(--ink);text-decoration:none}.block a:hover{color:var(--accent)}.t-foot{background:#111;color:#666;padding:18px 0;font-size:13px}$CSS$);
